/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Autor;
import Clases.Genero;
import Clases.Libro;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author vladi
 */
public class Crear extends javax.swing.JFrame {
    
    int modus = 0;
    /**
     * Creates new form Crear
     * @param modus
     */
    public Crear(int modus) {
        initComponents();
        this.modus = modus;
        
        ArrayList<String> generos = new ArrayList<>(SQL.Buscar.generos);
        generos.add("Agregar...");
        CBgenero.setModel(new DefaultComboBoxModel(generos.toArray()));
 
        switch(modus){
            case 0 -> {
                ArrayList<String> autores = new ArrayList<>(SQL.Buscar.autores);
                autores.add("Agregar...");
                CBautor.setModel(new DefaultComboBoxModel(autores.toArray()));
            }
            case 1 -> {
                Ltitulo.setText("Agregar autor");
                Lautor.setVisible(false);
                CBautor.setVisible(false);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ltitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Lnombre = new javax.swing.JLabel();
        Lgenero = new javax.swing.JLabel();
        Lautor = new javax.swing.JLabel();
        TFnombre = new javax.swing.JTextField();
        CBgenero = new javax.swing.JComboBox<>();
        CBautor = new javax.swing.JComboBox<>();
        BTNlimpiar = new javax.swing.JButton();
        BTNagregar = new javax.swing.JButton();
        BTNcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Ltitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ltitulo.setText("Agregar Libro");

        Lnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lnombre.setText("Nombre");

        Lgenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lgenero.setText("Genero");

        Lautor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lautor.setText("Autor");

        TFnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CBgenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PlaceHolder" }));
        CBgenero.setSelectedIndex(-1);
        CBgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBgeneroActionPerformed(evt);
            }
        });

        CBautor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBautor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PlaceHolder" }));
        CBautor.setSelectedIndex(-1);
        CBautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBautorActionPerformed(evt);
            }
        });

        BTNlimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTNlimpiar.setText("Limpiar");
        BTNlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlimpiarActionPerformed(evt);
            }
        });

        BTNagregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTNagregar.setText("Agregar");
        BTNagregar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BTNagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNagregarActionPerformed(evt);
            }
        });

        BTNcancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTNcancelar.setText("Cancelar");
        BTNcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lnombre)
                            .addComponent(Lgenero)
                            .addComponent(Lautor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBgenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TFnombre)
                            .addComponent(CBautor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ltitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 242, Short.MAX_VALUE)
                        .addComponent(BTNcancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNlimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNagregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnombre)
                    .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lgenero)
                    .addComponent(CBgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lautor)
                            .addComponent(CBautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNagregar)
                            .addComponent(BTNlimpiar)
                            .addComponent(BTNcancelar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBgeneroActionPerformed
       if(CBgenero.getSelectedIndex() != -1){
            if(CBgenero.getSelectedItem().toString().equals("Agregar...")){
                String genero = JOptionPane.showInputDialog(null, "Ingrese el nombre del nuevo genero", "Agregar genero", JOptionPane.QUESTION_MESSAGE);
           
                if(!genero.isEmpty()){
                    new Genero().crear(new String[] {genero});
                    ArrayList<String> generos = new ArrayList<>(SQL.Buscar.generos);
                    generos.add("Agregar...");
                    CBgenero.setModel(new DefaultComboBoxModel(generos.toArray()));
                }
            }
       }
    }//GEN-LAST:event_CBgeneroActionPerformed

    private void CBautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBautorActionPerformed
        if(CBautor.getSelectedIndex() != -1){
            if(CBautor.getSelectedItem().toString().equals("Agregar...")){
                this.dispose();
                new Crear(1).setVisible(true);
            }
        }
    }//GEN-LAST:event_CBautorActionPerformed

    private void BTNagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNagregarActionPerformed
        if(modus == 0){
            new Libro().crear(new String[] {TFnombre.getText(), CBgenero.getSelectedItem().toString(), CBautor.getSelectedItem().toString()});
            
            this.dispose();
        
        }else if(modus == 1){
            new Autor().crear(new String[] {TFnombre.getText(), CBgenero.getSelectedItem().toString()});
            
            this.dispose();
            new Crear(0).setVisible(true);
        }
    }//GEN-LAST:event_BTNagregarActionPerformed

    private void BTNlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlimpiarActionPerformed
        TFnombre.setText("");
        CBgenero.setSelectedIndex(-1);
        CBautor.setSelectedIndex(-1);
    }//GEN-LAST:event_BTNlimpiarActionPerformed

    private void BTNcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Crear(0).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNagregar;
    private javax.swing.JButton BTNcancelar;
    private javax.swing.JButton BTNlimpiar;
    private javax.swing.JComboBox<String> CBautor;
    private javax.swing.JComboBox<String> CBgenero;
    private javax.swing.JLabel Lautor;
    private javax.swing.JLabel Lgenero;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
