/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Autor;
import Clases.Genero;
import Clases.Libro;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author vladi
 */
public class Modificar extends javax.swing.JFrame {
    
    /**
     * Creates new form Modificar
     */
    int modus = 0;
    String Nombreentrado = "";
    
    public Modificar(int modus, String nombre) {
        initComponents();
        this.modus = modus;
        this.Nombreentrado = nombre;
        
        ArrayList<String> generos = new ArrayList<>(SQL.Buscar.generos);
        generos.add("Agregar...");
        CBgenero.setModel(new DefaultComboBoxModel(generos.toArray()));
        
        switch(modus){
            case 0 -> {
                Ltitulo.setText("Modificar libro");
                
                ArrayList<String> autores = new ArrayList<>(SQL.Buscar.autores);
                autores.add("Agregar...");
                CBautor.setModel(new DefaultComboBoxModel(autores.toArray()));
                
                TFnombre.setText(nombre);
                
                for(int i = 0; i < Libro.libros.size(); i++){
                    if(Libro.libros.get(i).getNombre().equals(nombre)){
                        CBgenero.setSelectedItem(Libro.libros.get(i).getGenero());
                        CBautor.setSelectedItem(Libro.libros.get(i).getAutor());
                    }
                }
            }
            
            case 1 -> {
                Ltitulo.setText("Modificar autor");
                Lautor.setVisible(false);
                CBautor.setVisible(false);
                
                TFnombre.setText(nombre);
                
                for(int i = 0; i < Autor.autores.size(); i++){
                    if(Autor.autores.get(i).getNombre().equals(nombre)){
                        CBgenero.setSelectedItem(Autor.autores.get(i).getGenero());
                        break;
                    }
                }
            }
            
            case 2 -> {
                Ltitulo.setText("Modificar genero");
                TFnombre.setText(nombre);
                Lgenero.setVisible(false);
                CBgenero.setVisible(false);
                Lautor.setVisible(false);
                CBautor.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lnombre = new javax.swing.JLabel();
        Lautor = new javax.swing.JLabel();
        Lgenero = new javax.swing.JLabel();
        Ltitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TFnombre = new javax.swing.JTextField();
        CBgenero = new javax.swing.JComboBox<>();
        CBautor = new javax.swing.JComboBox<>();
        BTNguardar = new javax.swing.JButton();
        BTNcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lnombre.setText("Nombre");

        Lautor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lautor.setText("Autor");

        Lgenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lgenero.setText("Genero");

        Ltitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ltitulo.setText("PlaceHolder");

        TFnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CBgenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placeholder" }));

        CBautor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBautor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placeholder" }));

        BTNguardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTNguardar.setText("Guardar");
        BTNguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNguardarActionPerformed(evt);
            }
        });

        BTNcancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTNcancelar.setText("Cancelar");
        BTNcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ltitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lnombre)
                            .addComponent(Lgenero)
                            .addComponent(Lautor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBgenero, 0, 308, Short.MAX_VALUE)
                            .addComponent(CBautor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TFnombre))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNcancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNguardar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnombre)
                    .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lgenero)
                    .addComponent(CBgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lautor)
                    .addComponent(CBautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNguardar)
                    .addComponent(BTNcancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNcancelarActionPerformed

    private void BTNguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNguardarActionPerformed
        switch(modus){
            case 0 -> {
                int id = 0;
                int idv = 0;
                for(int i = 0; i < Libro.libros.size(); i++){
                    if(Libro.libros.get(i).getNombre().equals(Nombreentrado)){
                        idv = i;
                        id = Libro.libros.get(i).getId();
                        break;
                    }
                }
                
                new Libro().actualizar(new String[] {String.valueOf(id),Libro.libros.get(idv).getNombre() ,TFnombre.getText(), CBgenero.getSelectedItem().toString(), CBautor.getSelectedItem().toString()});
                this.dispose();
            }
            
            case 1 -> {
                int idv = 0;
                int id = 0;
                for(int i = 0; i < Autor.autores.size(); i++){
                    if(Autor.autores.get(i).getNombre().equals(Nombreentrado)){
                        idv = i;
                        id = Autor.autores.get(i).getId();
                        break;
                    }
                }
                
                new Autor().actualizar(new String[] {String.valueOf(id),Autor.autores.get(idv).getNombre() ,TFnombre.getText(), CBgenero.getSelectedItem().toString()});
                this.dispose();
            }
            
            case 2 -> {
                int idv = 0;
                for(int i = 0; i < Genero.generos.size(); i++){
                    if(Genero.generos.get(i).getNombre().equals(Nombreentrado)){
                        idv = i;
                        break;
                    }
                }
                
                new Genero().actualizar(new String[] {Genero.generos.get(idv).getNombre(), TFnombre.getText()});
                this.dispose();
            }

        }
    }//GEN-LAST:event_BTNguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Modificar(0, "").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNcancelar;
    private javax.swing.JButton BTNguardar;
    private javax.swing.JComboBox<String> CBautor;
    private javax.swing.JComboBox<String> CBgenero;
    private javax.swing.JLabel Lautor;
    private javax.swing.JLabel Lgenero;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
