package Interfaz;

import Clases.Autor;
import Clases.Genero;
import Clases.Libro;
import Clases.Utilidades;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vladi
 */
public class Pantalla_principal extends javax.swing.JFrame {
    
    String[] filtrolibro = {"Nombre","autor", "genero"};
    String[] filtroautor = {"nombre","genero", "libro"};
    String[] libroscolumn = {"ID","Nombre", "Genero", "Autor"};
    String[] autorcolumn = {"ID","Nombre", "Genero", "Libro preferencial"};
    /**
     * Creates new form Pantalla_principal
     */
    public Pantalla_principal() {
        initComponents();
        SQL.Buscar.getAutoresSimple();
        Libro.cargar();
        Autor.cargar();
        Genero.cargar();
        
        Tdata.setModel(new DefaultTableModel(Utilidades.toTableL(Libro.libros),libroscolumn));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        BTNGbuscar = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdata = new javax.swing.JTable();
        CBfiltro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TFbuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MInuevo = new javax.swing.JMenuItem();
        MIguardar = new javax.swing.JMenuItem();
        MIrefrescar = new javax.swing.JMenuItem();
        Mmodificar = new javax.swing.JMenu();
        MIMgenero = new javax.swing.JMenuItem();
        MIMautor = new javax.swing.JMenuItem();
        MIMlibro = new javax.swing.JMenuItem();
        Meliminar = new javax.swing.JMenu();
        MIEgenero = new javax.swing.JMenuItem();
        MIEautor = new javax.swing.JMenuItem();
        MIElibro = new javax.swing.JMenuItem();
        Mbuscar = new javax.swing.JMenu();
        MIlibro = new javax.swing.JCheckBoxMenuItem();
        MIautor = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PlaceHolder1", "PlaceHolder2", "PlaceHolder3", "PlaceHolder4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tdata);

        CBfiltro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBfiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "autor", "genero" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Buscar por:");

        TFbuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFbuscar.setText("Presione enter para buscar");
        TFbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFbuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Buscar:");

        jMenu2.setText("Archivo");

        MInuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MInuevo.setText("Nuevo");
        MInuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MInuevoActionPerformed(evt);
            }
        });
        jMenu2.add(MInuevo);

        MIguardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MIguardar.setText("Guardar");
        MIguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIguardarActionPerformed(evt);
            }
        });
        jMenu2.add(MIguardar);

        MIrefrescar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MIrefrescar.setText("Refrescar");
        MIrefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIrefrescarActionPerformed(evt);
            }
        });
        jMenu2.add(MIrefrescar);

        Mmodificar.setText("Modificar");

        MIMgenero.setText("Genero");
        MIMgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIMgeneroActionPerformed(evt);
            }
        });
        Mmodificar.add(MIMgenero);

        MIMautor.setText("Autor");
        MIMautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIMautorActionPerformed(evt);
            }
        });
        Mmodificar.add(MIMautor);

        MIMlibro.setText("Libro");
        MIMlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIMlibroActionPerformed(evt);
            }
        });
        Mmodificar.add(MIMlibro);

        jMenu2.add(Mmodificar);

        Meliminar.setText("Eliminar");

        MIEgenero.setText("Genero");
        MIEgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIEgeneroActionPerformed(evt);
            }
        });
        Meliminar.add(MIEgenero);

        MIEautor.setText("Autor");
        MIEautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIEautorActionPerformed(evt);
            }
        });
        Meliminar.add(MIEautor);

        MIElibro.setText("Libro");
        MIElibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIElibroActionPerformed(evt);
            }
        });
        Meliminar.add(MIElibro);

        jMenu2.add(Meliminar);

        Mbuscar.setText("Buscar");

        MIlibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BTNGbuscar.add(MIlibro);
        MIlibro.setSelected(true);
        MIlibro.setText("Libro");
        MIlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIlibroActionPerformed(evt);
            }
        });
        Mbuscar.add(MIlibro);

        MIautor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BTNGbuscar.add(MIautor);
        MIautor.setText("Autor");
        MIautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIautorActionPerformed(evt);
            }
        });
        Mbuscar.add(MIautor);

        jMenu2.add(Mbuscar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TFbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void TFbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFbuscarActionPerformed
        if(TFbuscar.getText().equals("Presione enter para buscar")){
            TFbuscar.setText("");
        }else{
            if(MIlibro.isSelected()){
                Tdata.setModel(new DefaultTableModel(Utilidades.FiltrarL(Libro.libros, CBfiltro.getSelectedItem().toString(), TFbuscar.getText()), libroscolumn));
            }else if(MIautor.isSelected()){
                Tdata.setModel(new DefaultTableModel(Utilidades.FiltrarA(Autor.autores, CBfiltro.getSelectedItem().toString(), TFbuscar.getText()), autorcolumn));
            }
        }
    }//GEN-LAST:event_TFbuscarActionPerformed

    private void MIautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIautorActionPerformed
        CBfiltro.setModel(new DefaultComboBoxModel(filtroautor));
        TFbuscar.setText("");
        Tdata.setModel(new DefaultTableModel(Utilidades.toTableA(Autor.autores),autorcolumn));
    }//GEN-LAST:event_MIautorActionPerformed

    private void MIlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIlibroActionPerformed
        CBfiltro.setModel(new DefaultComboBoxModel(filtrolibro));
        TFbuscar.setText("");
        Tdata.setModel(new DefaultTableModel(Utilidades.toTableL(Libro.libros),libroscolumn));
    }//GEN-LAST:event_MIlibroActionPerformed

    private void MIrefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIrefrescarActionPerformed
        if(MIlibro.isSelected()){
            Tdata.setModel(new DefaultTableModel(Utilidades.toTableL(Libro.libros),libroscolumn));
        }else if(MIautor.isSelected()){
            Tdata.setModel(new DefaultTableModel(Utilidades.toTableA(Autor.autores),autorcolumn));
        }
    }//GEN-LAST:event_MIrefrescarActionPerformed

    private void MIguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIguardarActionPerformed
        SQL.Guardado.guardar();
    }//GEN-LAST:event_MIguardarActionPerformed

    private void MInuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MInuevoActionPerformed
        new Crear(0).setVisible(true);
    }//GEN-LAST:event_MInuevoActionPerformed

    private void MIElibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIElibroActionPerformed
        int sl = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del libro a eliminar"));
        int val = 0;
        for(int i = 0; i < Libro.libros.size(); i++){
            if(Libro.libros.get(i).getId() == sl){
                val = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere eliminar el libro " + Libro.libros.get(i).getNombre() + "?");
                break;
            }
        }
        
        if(val == JOptionPane.YES_OPTION){
            new Libro().eliminar(sl);
        }
    }//GEN-LAST:event_MIElibroActionPerformed

    private void MIEautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIEautorActionPerformed
        int sl = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del autor a eliminar"));
        int val = 0;
        for(int i = 0; i < Autor.autores.size(); i++){
            if(Autor.autores.get(i).getId() == sl){
                val = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere eliminar al autor " + Autor.autores.get(i).getNombre() + "?");
            }
        }
        if(val == JOptionPane.YES_OPTION){
            new Autor().eliminar(sl);
        }
    }//GEN-LAST:event_MIEautorActionPerformed
    
    
    private void MIEgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIEgeneroActionPerformed
        int sl = JOptionPane.showOptionDialog(null, "Seleccione el genero a eliminar", "Eliminar genero", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, SQL.Buscar.generos.toArray(), EXIT_ON_CLOSE);
        
        if(sl != JOptionPane.CLOSED_OPTION){
            int val = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere eliminar al genero " + SQL.Buscar.generos.get(sl) + "?");
            
            if(val == JOptionPane.YES_OPTION){
                for(int i = 0; i < Genero.generos.size(); i++){
                    if(Genero.generos.get(i).getNombre().equals(SQL.Buscar.generos.get(sl))){
                        new Genero().eliminar(Genero.generos.get(i).getId());
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_MIEgeneroActionPerformed

    private void MIMgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIMgeneroActionPerformed
        int sl = JOptionPane.showOptionDialog(null, "Seleccione el genero a modificar", "Modificar genero", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, SQL.Buscar.generos.toArray(), EXIT_ON_CLOSE);
        
        if(sl != JOptionPane.CLOSED_OPTION){
            for(int i = 0; i < Genero.generos.size(); i++){
                if(Genero.generos.get(i).getNombre().equals(SQL.Buscar.generos.get(sl))){
                    new Modificar(2, Genero.generos.get(i).getNombre()).setVisible(true);
                    break;
                }
            }
        }
    }//GEN-LAST:event_MIMgeneroActionPerformed

    private void MIMautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIMautorActionPerformed
        int sl = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del autor a modificar"));
        for(int i = 0; i < Autor.autores.size(); i++){
            if(Autor.autores.get(i).getId() == sl){
                new Modificar(1, Autor.autores.get(i).getNombre()).setVisible(true);
                break;
            }
        }
        
        
    }//GEN-LAST:event_MIMautorActionPerformed

    private void MIMlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIMlibroActionPerformed
        int sl = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del libro a modificar"));
        for(int i = 0; i < Libro.libros.size(); i++){
            if(Libro.libros.get(i).getId() == sl){
                new Modificar(0, Libro.libros.get(i).getNombre()).setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_MIMlibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pantalla_principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTNGbuscar;
    private javax.swing.JComboBox<String> CBfiltro;
    private javax.swing.JMenuItem MIEautor;
    private javax.swing.JMenuItem MIEgenero;
    private javax.swing.JMenuItem MIElibro;
    private javax.swing.JMenuItem MIMautor;
    private javax.swing.JMenuItem MIMgenero;
    private javax.swing.JMenuItem MIMlibro;
    private javax.swing.JCheckBoxMenuItem MIautor;
    private javax.swing.JMenuItem MIguardar;
    private javax.swing.JCheckBoxMenuItem MIlibro;
    private javax.swing.JMenuItem MInuevo;
    private javax.swing.JMenuItem MIrefrescar;
    private javax.swing.JMenu Mbuscar;
    private javax.swing.JMenu Meliminar;
    private javax.swing.JMenu Mmodificar;
    private javax.swing.JTextField TFbuscar;
    private javax.swing.JTable Tdata;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
